### ISSUE TITLE
Can't install cupy==7.8.0

### ISSUE THREAD

**Issue by AlexiaJM** [cupy/cupy#6933]
### Description

Chainer uses cupy == 7.8.0, I'm not sure if newer versions would work.

Option 1:
`pip install cupy==7.8.0`

>         CUDA_PATH       : /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/cudacore/11.0.2
>         NVTOOLSEXT_PATH : (none)
>         NVCC            : (none)
>         ROCM_HOME       : (none)
> 
>       Modules:
>         cuda      : Yes (version 11000)
>         cusolver  : Yes
>         cudnn     : Yes (version 8003)
>         nccl      : No
>           -> Include files not found: ['nccl.h']
>           -> Check your CFLAGS environment variable.
>         nvtx      : Yes
>         thrust    : Yes
>         cutensor  : No
>           -> Include files not found: ['cutensor.h']
>           -> Check your CFLAGS environment variable.
>         cub       : Yes
> 
>       WARNING: Some modules could not be configured.
>       CuPy will be installed without these modules.
>       Please refer to the Installation Guide for details:
>       https://docs.cupy.dev/en/stable/install.html
> 
>       ************************************************************
> 
>       NOTICE: Skipping cythonize as cupy/core/_dtype.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/_kernel.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/_memory_range.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/_routines_indexing.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/_routines_logic.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/_routines_manipulation.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/_routines_math.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/_routines_sorting.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/_routines_statistics.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/_scalar.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/core.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/dlpack.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/flags.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/internal.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/fusion.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/raw.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/cublas.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/cufft.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/curand.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/cusparse.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/device.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/driver.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/memory.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/memory_hook.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/nvrtc.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/pinned_memory.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/profiler.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/function.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/stream.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/runtime.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/texture.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/util.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/cusolver.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/cudnn.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cudnn.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/nvtx.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/thrust.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/cub.pyx does not exist.
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/tmp/pip-install-3nvzj2jg/cupy_b0144fd6a6cf445885b7f609ca09f2cc/setup.py", line 156, in <module>
>           setup(
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
>           return distutils.core.setup(**attrs)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 177, in setup
>           return run_commands(dist)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
>           dist.run_commands()
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
>           self.run_command(cmd)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
>           super().run_command(command)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
>           cmd_obj.run()
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/command/install.py", line 68, in run
>           return orig.install.run(self)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/command/install.py", line 695, in run
>           self.run_command('build')
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
>           self.distribution.run_command(command)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
>           super().run_command(command)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
>           cmd_obj.run()
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/command/build.py", line 24, in run
>           super().run()
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
>           self.run_command(cmd_name)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
>           self.distribution.run_command(command)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
>           super().run_command(command)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
>           cmd_obj.run()
>         File "/tmp/pip-install-3nvzj2jg/cupy_b0144fd6a6cf445885b7f609ca09f2cc/cupy_setup_build.py", line 991, in run
>           check_extensions(self.extensions)
>         File "/tmp/pip-install-3nvzj2jg/cupy_b0144fd6a6cf445885b7f609ca09f2cc/cupy_setup_build.py", line 728, in check_extensions
>           raise RuntimeError('''\
>       RuntimeError: Missing file: cupy/cuda/cub.cpp
>       Please install Cython 0.28.0 or later. Please also check the version of Cython.
>       See https://docs.cupy.dev/en/stable/install.html for details.

I have Cython 0.29.31, pip install says that 0.28.0 is not available so I can't downgrade.

Option 2:
`pip install cupy` or install from a git clone with `pip install -e .` 
Install properly, but chainer does not think that cupy is properly installed and I get cupy.core not found errors

Option 3:
`pip install cupy-cuda110`
ERROR: Could not find a version that satisfies the requirement cupy-cuda110 (from versions: none)
ERROR: No matching distribution found for cupy-cuda110

I think using version 7.8.0 of cupy would make it work with chainer, but I can't install it.

### To Reproduce

```py
pip install cupy==7.8.0 # error
pip install cupy-cuda110 # error not found
pip install cupy # works

pip install chainer
python -c 'import chainer; chainer.print_runtime_info()' # cupy not recognized by chainer
```

### Installation

Source (`pip install cupy`)

### Environment

```
OS                           : Linux-3.10.0-1160.62.1.el7.x86_64-x86_64-with-glibc2.2.5
Python Version               : 3.8.10
CuPy Version                 : 11.0.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.23.0
SciPy Version                : 1.8.0
Cython Build Version         : 0.29.31
Cython Runtime Version       : 0.29.31
CUDA Root                    : /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/cudacore/11.0.2
nvcc PATH                    : /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/cudacore/11.0.2/bin/nvcc
CUDA Build Version           : 11040
CUDA Driver Version          : 11060
CUDA Runtime Version         : 11040
cuBLAS Version               : (available)
cuFFT Version                : 10502
cuRAND Version               : 10205
cuSOLVER Version             : (11, 2, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 4)
Thrust Version               : 101201
CUB Build Version            : 101201
Jitify Build Version         : d90e2e0
cuDNN Build Version          : 8200
cuDNN Version                : 8200
NCCL Build Version           : 21104
NCCL Runtime Version         : 21104
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Tesla V100-SXM2-16GB
Device 0 Compute Capability  : 70
Device 0 PCI Bus ID          : 0000:1C:00.0
Device 1 Name                : Tesla V100-SXM2-16GB
Device 1 Compute Capability  : 70
Device 1 PCI Bus ID          : 0000:1D:00.0
```

**Comment by emcastillo** [comment]
First, you have cuda 11.4 installed, so you need to use `cupy-cuda114` for v9 & v10 or `cupy-cuda11x` for v11.

The reason you couldn't build 7.8.0 from the source is because Cython is not installed.
```
  Please install Cython 0.28.0 or later. Please also check the version of Cython.
```
`pip install Cython==0.29.4` should solve this.

Also the CuPy version limitation for Chainer was eased and we allow newer CuPy versions to work with Chainer.
However as Chainer development is no longer active, we don't ensure fully compatibility but it should work for most of the features. You can ignore `chainer.print_runtime_info()` errors.

**Comment by AlexiaJM** [comment]
@emcastillo Thanks for trying to help. 

As you can see in the environment I shared, I have Cython 0.29.31 already, version 0.29.4 is unavailable in my pip install. So that does not explain the source error since it is installed, I cannot install the older versions of cupy even with Cython installed.

Regarding cuda, my version is 11.0.2 as can be seen above, not 11.4. And I mentioned above that pip install cupy-cuda110 does not work, its the same for any cupy-cudaxxx, they are not available for me in pip, I don't know why. So I can only pip install cupy.

With this cupy (latest from pip install and I also tried from source directly from the GitHub), all his fine when using cupy, but chainer does not recognize this cupy and give many errors. Hence, why I thought that maybe I should be using the older cupy version used in chainer; but i get an error saying that Cython is not installed when it is installed.

**Comment by leofang** [comment]
It looks like you're using a cluster. What do you get when you do `python -m pip --version`? I have a feeling that the default Python may be outdated, thus leading to the version not found error with `cupy-cuda110`.

**Comment by AlexiaJM** [comment]
pip 22.2.1, I updated it before. I don't know why it cannot find cupy-cudaxxxx.

**Comment by leofang** [comment]
What's the Python version that `pip` reports?

**Comment by leofang** [comment]
btw could you post the full output when you do `pip install "cupy-cuda110==7.8.*"`?

**Comment by AlexiaJM** [comment]
> pip 22.2.1 from /home/jolicoea/vidgen2/lib/python3.8/site-packages/pip (python 3.8)

> (vidgen2) [jolicoea@beluga4 ~]$ pip install "cupy-cuda110==7.8.*"
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo/avx512, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo/generic, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
ERROR: Could not find a version that satisfies the requirement cupy-cuda110==7.8.* (from versions: none)
ERROR: No matching distribution found for cupy-cuda110==7.8.*

> (vidgen2) [jolicoea@beluga4 ~]$ pip install cupy==cupy-cuda11x
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo/avx512, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo/generic, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
ERROR: Could not find a version that satisfies the requirement cupy==cupy-cuda11x (from versions: 1.0.0a1, 1.0.0b1, 1.0.0.1, 1.0.1, 1.0.2, 1.0.3, 2.0.0a1, 2.0.0b1, 2.0.0rc1, 2.0.0, 2.1.0, 2.1.0.1, 2.2.0, 2.3.0, 2.4.0, 2.5.0, 3.0.0a1, 4.0.0b1, 4.0.0b2, 4.0.0b3, 4.0.0b4, 4.0.0rc1, 4.0.0, 4.1.0, 4.2.0, 4.3.0, 4.4.0, 4.4.1, 4.5.0, 5.0.0a1, 5.0.0b1, 5.0.0b2, 5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.3.0, 5.4.0, 6.0.0a1, 6.0.0b1, 6.0.0b2, 6.0.0b3, 6.0.0rc1, 6.0.0, 6.1.0, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0a1, 7.0.0b1, 7.0.0b2, 7.0.0b3, 7.0.0b4, 7.0.0rc1, 7.0.0, 7.1.0, 7.1.1, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.7.0, 7.8.0, 7.8.0.post1, 8.0.0a1, 8.0.0b1, 8.0.0b2, 8.0.0b3, 8.0.0b4, 8.0.0b5, 8.0.0rc1, 8.0.0, 8.1.0, 8.1.0+computecanada, 8.2.0, 8.3.0, 8.4.0, 8.5.0, 8.6.0, 9.0.0a1, 9.0.0a2, 9.0.0b1, 9.0.0b2, 9.0.0b3, 9.0.0rc1, 9.0.0, 9.1.0, 9.2.0, 9.3.0, 9.4.0, 9.5.0, 9.5.0+computecanada, 9.6.0, 9.6.0+computecanada, 10.0.0a1, 10.0.0a2, 10.0.0b1, 10.0.0b2, 10.0.0b3, 10.0.0rc1, 10.0.0, 10.1.0, 10.2.0, 10.2.0+computecanada, 10.3.0, 10.3.1, 10.4.0, 10.5.0, 10.6.0, 10.6.0+computecanada, 11.0.0a1, 11.0.0a2, 11.0.0b1, 11.0.0b2, 11.0.0b3, 11.0.0rc1, 11.0.0, 11.0.0+computecanada)
ERROR: No matching distribution found for cupy==cupy-cuda11x

**Comment by leofang** [comment]
Thanks @AlexiaJM. You need to reach out to your cluster admins. Apparently your admins block `https://pypi.org/simple` so that `pip install` cannot look up the public index. There's nothing we can do. 

You may edit the local index search list (ex: `~/.pip/pip.conf`, or just `pip install --extra-index-url=https://pypi.org/simple`, but I'd still suggest you to check with your admins first, as they might do it for a reason.

**Comment by AlexiaJM** [comment]
thanks @leofang, I'll reach out to them!

**Comment by leofang** [comment]
Another note: `pip install cupy` installs the sdist and builds from source, and the real error is this line
```
RuntimeError: Missing file: cupy/cuda/cub.cpp
```
not related to Cython. We might have made a mistake in the early days and forgot to include the `cub.cpp` file in the sdist. It's been a while so I could be wrong, but I'm pretty sure it's fixed in a later version (after 7.x). Not sure if clearing out the old env var `CUB_PATH` helps or not. Others from the team can comment...

**Comment by kmaehashi** [comment]
v7.8.0 sdist was broken and we have a hotfix as v7.8.0.post1.

https://github.com/cupy/cupy/releases/v7.8.0.post1
https://pypi.org/project/cupy/#history

So `pip install cupy==v7.8.0.post1` in case you need CuPy v7.8.0.

**Comment by AlexiaJM** [comment]
Problem solved!

pip install cupy==v7.8.0.post1 did not work, but git cloning v7 of cupy allow you to install it properly with no error.

However, the chainer bug remains with v7 of cupy! The reason was that I only had chainer 4.5.0, a very old version. I asked the managers of the cluster to update the pip, in the meantime **installing the latest chainer (through git clone) and the latest cupy (through git clone)** is the solution!
